CREATE TABLE alumnos (
    id SERIAL PRIMARY KEY,
    email TEXT,
    dni TEXT,
    apellido TEXT,
    nombre TEXT,
    celular TEXT,
    celular_alt TEXT,
    fecha_nac TEXT,
    cursado_anterior TEXT,
    turno TEXT,
    cursa_actualmente TEXT,
    institucion TEXT,
    nombre_institucion TEXT,
    localidad_provincia TEXT,
    materias_totales TEXT,
    materias_a_rendir TEXT,
    materias TEXT,
    preferencia_materias TEXT,
    observaciones TEXT,
    genero TEXT,
    egreso_fines TEXT,
    cursado_2023 TEXT
);
